name: Version Check and Release Creating

on:
  push:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.version.outputs.changed }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for Version Update
        id: version
        uses: EndBug/version-check@v2.1.4
        with:
          file-url: https://unpkg.com/@rnbws/rfrncs.design/package.json
          static-checking: localIsNew

  create-release:
    needs: version-check
    if: needs.version-check.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag and GitHub Release
        if: needs.version-check.outputs.changed == 'true'
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v${{  needs.version-check.outputs.version }}
          release_name: Release v${{  needs.version-check.outputs.version }}
